# Google Cloud Build configuration for automated deployment
# Builds Docker image and deploys to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aibc-auth:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aibc-auth:latest'
      - '-f'
      - 'aibc_auth/Dockerfile'
      - 'aibc_auth/'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aibc-auth:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aibc-auth-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aibc-auth:$COMMIT_SHA'
      - '--region'
      - 'us-central1'  # Change to your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove if you want authentication required
      - '--min-instances'
      - '1'  # Always keep 1 instance warm (reduces cold starts)
      - '--max-instances'
      - '10'  # Max 10 instances for 60 users (plenty of headroom)
      - '--cpu'
      - '1'  # 1 vCPU per instance
      - '--memory'
      - '512Mi'  # 512MB RAM (sufficient for FastAPI)
      - '--concurrency'
      - '80'  # 80 concurrent requests per instance
      - '--timeout'
      - '60'  # 60 second timeout
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,JWT_REFRESH_SECRET_KEY=JWT_REFRESH_SECRET_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/aibc-auth:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/aibc-auth:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'  # Faster builds
