version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aibc_postgres
    environment:
      POSTGRES_DB: aibc_db
      POSTGRES_USER: aibc_admin
      POSTGRES_PASSWORD: AIbc2024SecureP@ss
    volumes:
      - ./init-complete.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aibc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aibc_admin -d aibc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth_service:
    build:
      context: ./aibc_auth
      dockerfile: Dockerfile
    container_name: aibc_auth
    env_file:
      - ./aibc_auth/.env
    environment:
      - DATABASE_URL=postgresql://aibc_admin:AIbc2024SecureP@ss@postgres:5432/aibc_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aibc_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  aibc_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local